### ISSUE TITLE
get codes new Kaku

### ISSUE THREAD

**Issue by poudenes** [robertklep/node-kaku-rpi#1]
Hi there,

I have the cheap 433mhz receiver and transmitter. Can i use them also to get the codes of my wall switches? I can program receivers to lean a new code, but want get the codes of my wall senders to put lights on.. want use same codes in my Homebridge config

**Comment by robertklep** [comment]
I've used an Arduino and one of the various "RC Switch" libraries for it to receive RF codes emitted by KaKu transmitters, so it's possible to receive the codes. I based a lot of code of this module on the [Remote Switch library from Randi Simons](https://bitbucket.org/fuzzillogic/433mhzforarduino/src/0847a6d8a9173abd5abf9cf571a1539f56588c0e/RemoteSwitch/).

However, this is only a partial solution, because the received codes are the "raw" codes transmitted by the devices, and not the address/device values that `node-kaku-rpi` needs (my module encodes address/device values to the raw code, but it doesn't have a decoder to do the reverse).

Can't you check what codes your wall transmitters are sending by removing the front plates?

**Comment by poudenes** [comment]
Hi there,

thanks for the feedback. There are no signs of a code inside the switches. Its new one of Kaku, they send a unique code to the receivers thats stands in learning mode.

Kind Regards,
Peter

**Comment by robertklep** [comment]
In that case, the Arduino-option may be the only way to determine the transmitter codes, but it's not a trivial exercise.

**Comment by poudenes** [comment]
Thanks

:) 
Peter
